#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "gutil.h"
#include "mutil.h"
#include "futil.h"




int main( int argc, char * argv[] )
{

/*-o-o-o-o-o-o-o some constants... o-o-o-o-o-o-o-o-*/

double done = 1.0000;

double dzero = 0.0000;


/*-o-o-o-o-o-o-o Variables... o-o-o-o-o-o-o-o-*/

register FILE * pg09hess , *pgmxhess ;

char g09hessname[ 100 ] , gmxhessname[ 100 ];

double * g09hess , * g09hess_tri , * gmxhess ;

int len_g09hessname , len_g09hessname_ext , len_gmxhessname ;

int len_g09hessFile ;


int natom , ncart ;

int icart , iatom ;

int itmp; double dtmp; char chartmp[ 100 ];

char * keyword;






/*-o-o-o-o-o-o-o Debugging... o-o-o-o-o-o-o-o-*/

FILE * debug;


/*-o-o-o-o-o-o-o-o Parsing the Command-Line Arguments o-o-o-o-o-o-o-o-o-*/

char ** pv ; pv = argv ;

if( argc == 1 )
{
  printf("\nUsage : %s [ input g09 Hessian file name (unit = Hartree/Bohr^2 )] [ output Hessian file name (unit = kJ/mol/nm^2 ) ] \n" , *argv  );

  exit( 221 );
}
else if( argc == 2 )
{
  strcpy( g09hessname , *( pv + 1 ) );

  len_g09hessname = strlen( g09hessname ) ;

  if( *( g09hessname + len_g09hessname - 4 ) == '.' )
    
    len_g09hessname_ext = 3 ;
 
  else if( *( g09hessname + len_g09hessname - 5 ) == '.' )
    
    len_g09hessname_ext = 4 ;
 
  else if( *( g09hessname + len_g09hessname - 3 ) == '.' )

    len_g09hessname_ext = 2 ;

  else
  {	   
    printf("\nCan't you just name your file regularly???\n");

    exit( 2 );
  }

  strncpy( gmxhessname , g09hessname , len_g09hessname - len_g09hessname_ext );
  
  *( gmxhessname + len_g09hessname - len_g09hessname_ext ) = '\0' ;

  strcat( gmxhessname , "cmw" );

}
else if( argc == 3 )
{
  printf("\nGood ... you have both input and output file names ... \n");

  strcpy( g09hessname , *( pv + 1 ) );

  strcpy( gmxhessname , *( pv + 2 ) );
}
else
{
  printf("\nToo many command-line arguments ...\n\n");

  exit( 8666269 );

}


if( ( pg09hess = fopen( g09hessname , "r" ) ) == NULL )
{
  printf("\nUser specified input Gaussian Hessian file does not exist ... \n");

  exit( 6 );
}

fsearch( pg09hess , "Dump" );

//fscanf( pg09hess , "%s" , chartmp );

//printf("\nNow we are at %s ... \n" , chartmp );

fskip( pg09hess , 1 );

register FILE * tmp2 ;

tmp2 = fopen( "modified_info.tmp" , "wb+" ); 

fsub( pg09hess , 'D', 'E', tmp2 );
  
rewind( tmp2 );

len_g09hessFile = flength( tmp2 );

ncart = ( sqrt( 1 + 8 * len_g09hessFile ) - 1 ) / 2 ;

itmp = ncart * ( ncart + 1 ) / 2 ;

if( itmp != len_g09hessFile )
{
  printf("\nThere are %d numbers in your Hessian file, so I thought ncart is %d ...\n" , len_g09hessFile , ncart );
  
  printf("\nLooks like your G09 Hessian file is not a regular one ... Go find a regular one ...\n");

  exit( 7 );
}
else
{
  fclose( tmp2 );
  
  fdel( "modified_info.tmp"  );
}

/*-o-o-o-o-o-o-o Allocating Space ... o-o-o-o-o-o-o-o-*/

g09hess_tri = ( double * ) calloc( len_g09hessFile , sizeof( double ) );

g09hess = ( double * ) calloc( ncart * ncart , sizeof( double ) );

gmxhess = ( double * ) calloc( ncart * ncart , sizeof( double ) );



/*-o-o-o-o-o-o-o ... Loading : Hessian, mass, cart_q0 ... o-o-o-o-o-o-o-o-*/

/* Loading ... */

rewind( pg09hess );

keyword="Dump";

//fscanf( pg09hess , "%s" , chartmp );

//printf("\nNow we are at %s ... \n" , chartmp );

pick( pg09hess, keyword, 1, g09hess_tri );


/* Change triangular Hessian(Cart) into symmetric matrix  */

dtri2sym( 'U', ncart, g09hess_tri, g09hess);



debug = fopen( "g09hess.hess" , "wb+" );

doutput( debug , ncart , ncart , g09hess );

fclose( debug );


/* Converting in progress ... */

for( itmp = 0 ; itmp < ncart * ncart ; itmp ++ )
{
  *( gmxhess + itmp ) = *( g09hess + itmp ) * 9.37582E5 ;
}


pgmxhess = fopen( gmxhessname , "wb+" );

fprintf( pgmxhess , "GROMACS Hessian File , unit = kJ/mol/(nm^2) , Generated by g09hess2gmx : \n %d %d \n" , ncart , ncart );

doutput( pgmxhess , ncart , ncart , gmxhess );

fclose( pgmxhess );


/*-o-o-o-o-o-o-o ... Em...What else? ... o-o-o-o-o-o-o-o-*/



return( 0 );

}






